build:
  script:
    - cmake ./
    - make
  tags:
    - cmake
  artifacts:
    paths:
    - ./NagyHF

image: alpine

pages:
  script:
  - apk update && apk add doxygen
  - ls
  - doxygen doxygen/Doxyfile
  - mv doxygen/documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master